project_id = "ntbnattqfhfqfdjrwmti"

[api]
enabled = true
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
major_version = 17

[storage]
enabled = true
file_size_limit = "2MiB"

[storage.buckets.grocery-images]
public = true
file_size_limit = "2MiB"
allowed_mime_types = ["image/png", "image/jpeg", "image/webp"]
objects_path = "./seed-assets/grocery-images"
